from django.conf.urls.defaults import *

urlpatterns = patterns('todo.views',
    url(r'^$', 'list', name='tasks_list'),
    url(r'^add_task/$', 'add_task', name='add_task'),
    url(r'^add_project/$', 'add_project', name='add_project'),
    url(r'^(?P<task_id>\d+)/add_comment/$', 'add_comment', name='add_comment'),
    url(r'^del_comment/(?P<comment_id>\d+)/$', 'del_comment', name='del_comment'),
    url(r'^projects/$', 'projects_list', name='projects_list'),
    url(r'^projects/(?P<project_id>\d+)/$', 'project_details', name='project_details'),
    url(r'^edit_project/(?P<project_id>\d+)/$', 'edit_project', name='edit_project'),
    url(r'^delete_project/(?P<project_id>\d+)/$', 'delete_project', name='delete_project'),
    url(r'^(?P<task_id>\d+)/$', 'details', name='task_details'),
    url(r'^edit/(?P<task_id>\d+)/$', 'edit', name='edit_task'),
    url(r'^delete/(?P<task_id>\d+)/$', 'delete', name='delete_task'),
    url(r'^task_to_accepted/(?P<task_id>\d+)/$', 'task_to_accepted', name='task_to_accepted'),
    url(r'^task_to_done/(?P<task_id>\d+)/$', 'task_to_done', name='task_to_done'),
    url(r'^task_to_checked/(?P<task_id>\d+)/$', 'task_to_checked', name='task_to_checked'),
    url(r'^task_to_new/(?P<task_id>\d+)/$', 'task_to_new', name='task_to_new'),
    url(r'^delete_project_attach/(?P<attach_id>\d+)/$', 'delete_project_attach', name='delete_project_attach'), 
    url(r'^delete_task_attach/(?P<attach_id>\d+)/$', 'delete_task_attach', name='delete_task_attach'),
)